version: '3'

services:
  quiz-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=quiz_db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
